# Generated by Django 3.2.3 on 2021-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_trip_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary_entry',
            options={'ordering': ['-date']},
        ),
    ]
