# Generated by Django 3.2.5 on 2021-07-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_trip_user'),
        ('main_app', '0006_remove_note_user'),
    ]

    operations = [
    ]
