# Generated by Django 3.2.3 on 2021-07-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='url',
        ),
    ]
